/*jslint node: true, nomen: true */
"use strict";

var ko = require('knockout');

exports.register = function () {
    require('./main-application').register();
    require('./c-vc-mainapp').register();
    require('./c-project-body').register();
    require('./auth/c-vc-edit-account').register();
    require('./auth/c-form-user-edit').register();
    require('./c-vc-authed-block').register();
    require('./auth/c-det-user-info').register();
    require('./c-xor-authed-role-block').register();
    require('./c-vc-worker-main').register();
    require('./c-xor-worker-workflow').register();
    require('./c-vc-task-list').register();
    require('./c-vc-task-details').register();
    require('./c-vc-task-statistic').register();
    require('./c-vc-task-session').register();
    require('./c-list-task').register();
    require('./c-det-task').register();
    require('./c-det-task-stat').register();
    require('./auth/c-vc-auth-block').register();
    require('./auth/c-xor-signup-register').register();
    require('./auth/c-vc-signup').register();
    require('./auth/c-vc-login').register();
    require('./auth/c-form-sign-up').register();
    require('./auth/c-form-login').register();
    require('./c-vc-manager-body').register();
    require('./c-xor-manager-workflow').register();
    require('./campaign/c-vc-add-campaign').register();
    require('./campaign/c-vc-campaign-statistic').register();
    require('./image/c-vc-image-details').register();
    require('./image/c-vc-image-list').register();
    require('./image/c-vc-image-upload').register();
    require('./c-vc-worker-list').register();
    require('./image/c-vc-image-stat').register();
    require('./campaign/c-form-new-campaign').register();
    require('./campaign/c-det-campaign-stat').register();
    require('./image/c-det-image').register();
    require('./image/c-list-image').register();
    require('./image/c-form-image-upload').register();
    require('./c-list-workers').register();
    require('./image/c-det-image-stat').register();
    require('./c-list-annotation').register();
    require('./campaign/c-vc-campaign-list').register();
    require('./campaign/c-list-campaigns').register();
    require('./campaign/c-vc-campaign-details').register();
    require('./campaign/c-det-campaign').register();
    require('./c-vc-worker-details').register();
    require('./c-det-worker').register();
    require('./c-form-task-submit').register();
};
