/*jslint node: true, nomen: true */
"use strict";

exports.createEvents = function (options) {
    return {
        'ev-logout-success': require('./ev-logout-success').createEvent(options)
        ,'ev-annotation-changed': require('./ev-annotation-changed').createEvent(options)
        ,'ev-delete-image-success': require('./ev-delete-image-success').createEvent(options)
        ,'ev-start-campaign-success': require('./ev-start-campaign-success').createEvent(options)
        ,'ev-stop-campaign-success': require('./ev-stop-campaign-success').createEvent(options)
        ,'ev-upload-image-success': require('./ev-upload-image-success').createEvent(options)
        ,'ev-user-update-success': require('./ev-user-update-success').createEvent(options)
        ,'ev-user-update-submit': require('./ev-user-update-submit').createEvent(options)
        ,'ev-selection-changed': require('./ev-selection-changed').createEvent(options)
        ,'ev-logout': require('./ev-logout').createEvent(options)
        ,'ev-edit-account': require('./ev-edit-account').createEvent(options)
        ,'ev-list-task-selected': require('./ev-list-task-selected').createEvent(options)
        ,'ev-task-session': require('./ev-task-session').createEvent(options)
        ,'ev-task-statistic': require('./ev-task-statistic').createEvent(options)
        ,'ev-signup-submit': require('./ev-signup-submit').createEvent(options)
        ,'ev-to-upload-image': require('./ev-to-upload-image').createEvent(options)
        ,'ev-delete-image': require('./ev-delete-image').createEvent(options)
        ,'ev-to-image-statistic': require('./ev-to-image-statistic').createEvent(options)
        ,'ev-image-selected': require('./ev-image-selected').createEvent(options)
        ,'ev-upload-image-submit': require('./ev-upload-image-submit').createEvent(options)
        ,'ev-list-worker': require('./ev-list-worker').createEvent(options)
        ,'ev-create-new-campaign': require('./ev-create-new-campaign').createEvent(options)
        ,'ev-list-campaign-selected': require('./ev-list-campaign-selected').createEvent(options)
        ,'ev-campaign-statistic': require('./ev-campaign-statistic').createEvent(options)
        ,'ev-campaign-images': require('./ev-campaign-images').createEvent(options)
        ,'ev-campaign-workers': require('./ev-campaign-workers').createEvent(options)
        ,'ev-start-campaign': require('./ev-start-campaign').createEvent(options)
        ,'ev-stop-campaign': require('./ev-stop-campaign').createEvent(options)
        ,'ev-login-success': require('./ev-login-success').createEvent(options)
        ,'ev-campaign-form-submit': require('./ev-campaign-form-submit').createEvent(options)
        ,'ev-login-form-submit': require('./ev-login-form-submit').createEvent(options)
        ,'ev-register-success': require('./ev-register-success').createEvent(options)
        ,'ev-tap-selection': require('./ev-tap-selection').createEvent(options)
        ,'ev-tap-annotation': require('./ev-tap-annotation').createEvent(options)
        ,'ev-submit-result-failure': require('./ev-submit-result-failure').createEvent(options)
        ,'ev-submit-result-success': require('./ev-submit-result-success').createEvent(options)
        ,'ev-start-session-success': require('./ev-start-session-success').createEvent(options)
        ,'ev-start-session-failure': require('./ev-start-session-failure').createEvent(options)
        ,'ev-task-submit': require('./ev-task-submit').createEvent(options)
        ,'act-create-campaign-success': require('./act-create-campaign-success').createEvent(options)
    };
};
